<?php

namespace App\Http\Controllers\Tenant;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\File;

/**
 * Path tenancy means every tenant's panel lives at a different URL
 * (/shop/{slug}/panel), so a single static manifest.json can't declare a
 * meaningful start_url/scope for everyone — each tenant needs their own,
 * pointing at their own panel, so "Add to Home Screen" from inside a
 * tenant's panel installs an app that actually opens back into that same
 * tenant's panel rather than the central marketing site. Served as JSON
 * from a normal authenticated route rather than a static public file for
 * exactly that reason. Icons/name/theme stay identical for every tenant —
 * this is still one MetaSoft app, not a per-tenant white-label build.
 *
 * Scope is deliberately the panel only (not the whole tenant site) — the
 * public storefront is a customer-facing catalog/checkout, not something
 * a merchant would "install" as their business app, and keeping the
 * service worker's own max-scope this narrow (see serviceWorker() below)
 * means it can never intercept a single storefront/checkout request.
 */
class PwaController extends Controller
{
    public function manifest()
    {
        $tenant = app('currentTenant');
        $panelUrl = $tenant->url().'/panel';

        return response()->json([
            'name' => 'MetaSoft SaaS',
            'short_name' => 'MetaSoft',
            'description' => 'MetaSoft — e-commerce ও ব্যবসা ব্যবস্থাপনা প্যানেল',
            'start_url' => $panelUrl,
            'scope' => $panelUrl.'/',
            'display' => 'standalone',
            'orientation' => 'portrait-primary',
            'background_color' => '#F4F2EA',
            'theme_color' => '#128155',
            'lang' => 'bn',
            'dir' => 'ltr',
            'icons' => [
                ['src' => asset('images/icons/icon-192.png'), 'sizes' => '192x192', 'type' => 'image/png', 'purpose' => 'any'],
                ['src' => asset('images/icons/icon-512.png'), 'sizes' => '512x512', 'type' => 'image/png', 'purpose' => 'any'],
                ['src' => asset('images/icons/icon-maskable-192.png'), 'sizes' => '192x192', 'type' => 'image/png', 'purpose' => 'maskable'],
                ['src' => asset('images/icons/icon-maskable-512.png'), 'sizes' => '512x512', 'type' => 'image/png', 'purpose' => 'maskable'],
            ],
        ], 200, ['Content-Type' => 'application/manifest+json']);
    }

    /**
     * Served from panel/sw.js (not public/sw.js) specifically so the
     * browser's default max-scope for this worker is /panel/* — it can
     * physically never register for, or intercept, anything outside the
     * panel even if the registration call below ever changed.
     *
     * Cache version is derived from Vite's own build manifest hash rather
     * than a number this code has to remember to bump — every `npm run
     * build` changes the hashed asset filenames, which changes this
     * derived version automatically, which makes activate() below purge
     * the previous cache and fetch the new hashed files. No separate
     * versioning scheme to keep in sync by hand.
     */
    public function serviceWorker()
    {
        $manifestPath = public_path('build/manifest.json');
        $shellUrls = [];
        $version = 'no-build';

        if (File::exists($manifestPath)) {
            $manifest = json_decode(File::get($manifestPath), true) ?? [];
            $version = substr(md5(File::get($manifestPath)), 0, 10);

            foreach ($manifest as $entry) {
                if (isset($entry['file'])) {
                    $shellUrls[] = asset('build/'.$entry['file']);
                }
                foreach ($entry['css'] ?? [] as $cssFile) {
                    $shellUrls[] = asset('build/'.$cssFile);
                }
            }
        }

        $shellUrls[] = asset('images/icons/icon-192.png');
        $shellUrls[] = asset('images/icons/icon-512.png');
        $shellUrls[] = asset('images/icons/apple-touch-icon.png');

        $cacheName = 'metasoft-shell-'.$version;
        $shellJson = json_encode(array_values(array_unique($shellUrls)));

        $js = <<<JS
// Auto-generated by PwaController::serviceWorker() — do not hand-edit.
// Cache version tracks the Vite build manifest hash, so a fresh
// `npm run build` + deploy is what rotates this, not a manual bump.
const CACHE_NAME = '{$cacheName}';
const APP_SHELL = {$shellJson};

self.addEventListener('install', (event) => {
    self.skipWaiting();
    event.waitUntil(
        caches.open(CACHE_NAME)
            .then((cache) => cache.addAll(APP_SHELL))
            .catch(() => {}) // a shell asset failing to precache must never block install
    );
});

self.addEventListener('activate', (event) => {
    event.waitUntil(
        caches.keys()
            .then((names) => Promise.all(
                names
                    .filter((name) => name.startsWith('metasoft-shell-') && name !== CACHE_NAME)
                    .map((name) => caches.delete(name))
            ))
            .then(() => self.clients.claim())
    );
});

// Security boundary: only ever cache-serve same-origin static build/icon
// assets. Every other GET (every panel page, every fetch/XHR to Orders,
// Messenger, Customers, Courier, notifications, etc.) is intentionally
// left untouched here and falls straight through to the network — this
// app has no public read-only API, so caching any of those responses
// would risk serving stale or cross-context private/tenant data. POST/
// PUT/DELETE requests (every form submission, every CSRF-bearing write)
// are never intercepted at all.
self.addEventListener('fetch', (event) => {
    const req = event.request;
    if (req.method !== 'GET') return;

    const url = new URL(req.url);
    const isStaticAsset = url.origin === self.location.origin
        && (url.pathname.startsWith('/build/') || url.pathname.startsWith('/images/icons/'));

    if (!isStaticAsset) return;

    event.respondWith(
        caches.match(req).then((cached) => cached || fetch(req).then((res) => {
            const copy = res.clone();
            caches.open(CACHE_NAME).then((cache) => cache.put(req, copy)).catch(() => {});
            return res;
        }))
    );
});

// Lets the page's own JS trigger the waiting worker to activate
// immediately when the user accepts the "new version available" prompt,
// instead of waiting for every tab to close on its own.
self.addEventListener('message', (event) => {
    if (event.data === 'SKIP_WAITING') self.skipWaiting();
});
JS;

        // No Service-Worker-Allowed header — the default max-scope (the
        // directory containing this script) is already exactly right for
        // both tenancy modes (/shop/{slug}/panel/ under path mode,
        // {slug}.domain/panel/ under subdomain mode); sending a header
        // that doesn't correctly account for the path-mode tenant prefix
        // would make the browser reject the registration outright.
        return response($js, 200, [
            'Content-Type' => 'application/javascript; charset=utf-8',
            'Cache-Control' => 'no-cache',
        ]);
    }
}
