<?php

namespace App\Services\Pwa;

use Illuminate\Support\Facades\File;

/**
 * Generates the single service-worker script served at both /panel/sw.js
 * (Tenant\PwaController) and /sw.js on the central domain
 * (PwaController::serviceWorker, the landing page's install button).
 *
 * The script's own logic never references a specific scope — its fetch
 * handler matches on request pathname patterns (/build/, /images/icons/),
 * not on anything relative to where it was registered — so the exact same
 * generated content is correct regardless of which of those two URLs
 * served it. Extracted here specifically so adding the landing-page PWA
 * surface didn't mean a second, hand-maintained copy of this logic.
 */
class PwaServiceWorkerBuilder
{
    public function build(): string
    {
        $manifestPath = public_path('build/manifest.json');
        $shellUrls = [];
        $version = 'no-build';

        if (File::exists($manifestPath)) {
            $manifest = json_decode(File::get($manifestPath), true) ?? [];
            $version = substr(md5(File::get($manifestPath)), 0, 10);

            foreach ($manifest as $entry) {
                if (isset($entry['file'])) {
                    $shellUrls[] = asset('build/'.$entry['file']);
                }
                foreach ($entry['css'] ?? [] as $cssFile) {
                    $shellUrls[] = asset('build/'.$cssFile);
                }
            }
        }

        $shellUrls[] = asset('images/icons/icon-192.png');
        $shellUrls[] = asset('images/icons/icon-512.png');
        $shellUrls[] = asset('images/icons/apple-touch-icon.png');

        // Manifest launcher-icon assets (see PwaController::manifest()) —
        // precached separately from icon-192/icon-512 above, which remain
        // the general MetaSoft brand mark used elsewhere and are not the
        // installed-app icon.
        $shellUrls[] = asset('images/icons/app-icon-192.png');
        $shellUrls[] = asset('images/icons/app-icon-512.png');
        $shellUrls[] = asset('images/icons/app-icon-maskable-192.png');
        $shellUrls[] = asset('images/icons/app-icon-maskable-512.png');

        $cacheName = 'metasoft-shell-'.$version;
        $shellJson = json_encode(array_values(array_unique($shellUrls)));

        return <<<JS
// Auto-generated by PwaServiceWorkerBuilder — do not hand-edit.
// Cache version tracks the Vite build manifest hash, so a fresh
// `npm run build` + deploy is what rotates this, not a manual bump.
const CACHE_NAME = '{$cacheName}';
const APP_SHELL = {$shellJson};

self.addEventListener('install', (event) => {
    self.skipWaiting();
    event.waitUntil(
        caches.open(CACHE_NAME)
            .then((cache) => cache.addAll(APP_SHELL))
            .catch(() => {}) // a shell asset failing to precache must never block install
    );
});

self.addEventListener('activate', (event) => {
    event.waitUntil(
        caches.keys()
            .then((names) => Promise.all(
                names
                    .filter((name) => name.startsWith('metasoft-shell-') && name !== CACHE_NAME)
                    .map((name) => caches.delete(name))
            ))
            .then(() => self.clients.claim())
    );
});

// Security boundary: only ever cache-serve same-origin static build/icon
// assets. Every other GET (every panel page, every fetch/XHR to Orders,
// Messenger, Customers, Courier, notifications, the central marketing
// site, registration, login, etc.) is intentionally left untouched here
// and falls straight through to the network — this app has no public
// read-only API, so caching any of those responses would risk serving
// stale or cross-context private/tenant data. POST/PUT/DELETE requests
// (every form submission, every CSRF-bearing write) are never
// intercepted at all.
self.addEventListener('fetch', (event) => {
    const req = event.request;
    if (req.method !== 'GET') return;

    const url = new URL(req.url);
    const isStaticAsset = url.origin === self.location.origin
        && (url.pathname.startsWith('/build/') || url.pathname.startsWith('/images/icons/'));

    if (!isStaticAsset) return;

    event.respondWith(
        caches.match(req).then((cached) => cached || fetch(req).then((res) => {
            const copy = res.clone();
            caches.open(CACHE_NAME).then((cache) => cache.put(req, copy)).catch(() => {});
            return res;
        }))
    );
});

// Lets the page's own JS trigger the waiting worker to activate
// immediately when the user accepts the "new version available" prompt,
// instead of waiting for every tab to close on its own.
self.addEventListener('message', (event) => {
    if (event.data === 'SKIP_WAITING') self.skipWaiting();
});
JS;
    }

    public function response(): \Illuminate\Http\Response
    {
        return response($this->build(), 200, [
            'Content-Type' => 'application/javascript; charset=utf-8',
            'Cache-Control' => 'no-cache',
        ]);
    }
}
